### ISSUE TITLE
Change icon Color

### ISSUE THREAD

**Issue by RaziPour1993** [LPZilva/Google-Material-Icons-for-Sketch#15]
Hi
How to change icon color in Sketch?
Thank you

**Comment by mattdetails** [comment]
Hi @RaziPour1993 - once you open up the sketch file, if you hold down CMD (On Mac), it'll allow you to quickly select the layers within groups. In some cases, it will select the "bound" layer - that's a hidden layer that you can't see, if you look over to the left at the layers panel, you should see the icon shape.

Once you have the icon shape selected, you should be seeing the ability to change colors on the right.

You just have to make sure you are selecting the very lowest layer of an icon, and making sure it is the shape of the icon.

See my screenshot of which layer I am talking about: https://mattdetails.d.pr/lPAg2Y

**Comment by LPZilva** [comment]
@RaziPour1993 @mattdetails I appreciate that you keep using this icon set repo, but since Google Design Team released a new set of icons a couple of months ago, I then stopped updating this GitHub repo. You may be interested in this:

• Filled Icons -
https://material.io/tools/theme-editor/downloads/icons/material-design-icons-filled.sketch

• Sharp Icons -
https://material.io/tools/theme-editor/downloads/icons/material-design-icons-sharp.sketch

• Rounded Icons -
https://material.io/tools/theme-editor/downloads/icons/material-design-icons-rounded.sketch

• Outlined Icons -
https://material.io/tools/theme-editor/downloads/icons/material-design-icons-outlined.sketch

• Two-tone Icons -
https://material.io/tools/theme-editor/downloads/icons/material-design-icons-two-tone.sketch
